import Reveal from './Reveal'
import ReactiveText from './ReactiveText'

function ProjectCard({ project, index }) {
  const visualOnRight = index % 2 === 0
  return <article id={`project-${index + 1}`} className="relative box-border flex min-h-[100vh] min-h-[100svh] flex-col justify-center pt-[var(--nav-h)] pb-[var(--nav-h)] scroll-mt-[var(--nav-h)]"><div className={`mx-auto grid w-full max-w-7xl items-center gap-12 px-5 py-20 lg:grid-cols-2 lg:gap-20 lg:px-8 ${visualOnRight ? '' : 'lg:[&>div:first-child]:order-2'}`}><Reveal variant={visualOnRight ? 'fade-right' : 'fade-left'}><div className="relative mx-auto w-full max-w-xl"><div className="relative z-[1] flex aspect-[4/3] items-center justify-center overflow-hidden rounded-3xl border border-[var(--border)] bg-[var(--surface)]">{project.image ? <img src={project.image} alt={`${project.title} project`} className="h-full w-full object-contain" /> : <div className="flex h-full w-full items-center justify-center rounded-2xl border border-[var(--border)] bg-[var(--surface-2)] text-7xl text-[var(--accent)]"><ProjectPlaceholder /></div>}</div><div className="absolute -bottom-3 -right-3 h-full w-full rounded-3xl border-2 border-[var(--accent)]" aria-hidden="true" /></div></Reveal><Reveal variant={visualOnRight ? 'fade-left' : 'fade-right'} delay={120}><div><p className="font-mono text-5xl font-bold text-[var(--accent)]">0{index + 1}</p><h2 className="mt-4 text-4xl font-bold tracking-tight sm:text-6xl"><ReactiveText text={project.title} /></h2><p className="mt-6 max-w-xl text-lg leading-8 text-[var(--muted)]"><ReactiveText text={project.description} mode="paragraph" /></p><div className="mt-7 flex flex-wrap gap-2">{project.tech.map((tag, tagIndex) => <Reveal key={`${tag}-${tagIndex}`} variant="scale-in" delay={180 + tagIndex * 70}><span className="inline-block rounded-full border border-[var(--border)] px-3 py-1 text-xs text-[var(--muted)]">{tag}</span></Reveal>)}</div><div className="mt-8 flex gap-4"><a href={project.links.source} className="rounded-full bg-[var(--accent)] px-5 py-3 text-sm font-semibold text-black transition-transform duration-200 hover:-translate-y-0.5">GitHub ↗</a><a href={project.links.live} className="rounded-full border border-[var(--accent)] px-5 py-3 text-sm font-semibold text-[var(--accent)] transition-transform duration-200 hover:-translate-y-0.5 hover:bg-[var(--accent)] hover:text-black">Demo ↗</a></div></div></Reveal></div></article>
}

function ProjectPlaceholder() { return <svg viewBox="0 0 120 120" className="h-28 w-28" fill="none" stroke="currentColor" strokeWidth="2" aria-label="Project placeholder"><path d="M20 78h80M30 78V44h60v34M42 44V30h36v14M50 30v-8h20v8M38 60h44" /><circle cx="40" cy="88" r="8" /><circle cx="80" cy="88" r="8" /></svg> }

export default ProjectCard
